package consts

import "time"

const (
	PROGRAM_FINISHED = 1
	PROGRAM_RUNNING  = 0

	ENDING_BYTE = 0x77

	ARCHITECTURE_SIZE = 32
	BITS_PER_BYTE     = 8
	BYTES_PER_WORD    = ARCHITECTURE_SIZE / BITS_PER_BYTE

	STATUS_REGISTER = 0
	FLAG_PARITY     = 2
	FLAG_ZERO       = 6
	FLAG_SIGN       = 7
	FLAG_OVERFLOW   = 11

	FETCH_CYCLES  = 1
	DECODE_CYCLES = 1

	FETCH_EVENT      = "F"
	DECODE_EVENT     = "D"
	EXECUTE_EVENT    = "E"
	ALU_EVENT        = "AL"
	LOAD_STORE_EVENT = "LS"
	BRANCH_EVENT     = "BR"

	WAIT_PERIOD = 10 * time.Microsecond
	MENU_DELAY  = 4 * time.Millisecond
)
