package consts

const (
	INSTRUCTION_REACHED_END = 1
	INSTRUCTION_OK          = 0
	INSTRUCTION_FAIL        = -1

	BITS_PER_BYTE  = 8
	BITS_PER_WORD  = 32
	BYTES_PER_WORD = BITS_PER_WORD / BITS_PER_BYTE

	ENDING_BYTE = 0x77

	STATUS_REGISTER = 0
	FLAG_PARITY     = 2
	FLAG_ZERO       = 6
	FLAG_SIGN       = 7
	FLAG_OVERFLOW   = 11
)
