package consts

const (
	INSTRUCTION_REACHED_END = 1
	INSTRUCTION_OK          = 0
	INSTRUCTION_FAIL        = -1

	BITS_PER_BYTE  = 8
	BITS_PER_WORD  = 32
	BYTES_PER_WORD = BITS_PER_WORD / BITS_PER_BYTE

	ENDING_BYTE = 0x77
)
